runtime: nodejs20
service: dev

env_variables:
  NODE_ENV: development
  GOOGLE_CLOUD_PROJECT: mol-analysis-app

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.8

# Development-specific settings
instance_class: F1
